# Generated by Django 5.1.1 on 2024-09-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Derecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('descripcion', models.TextField()),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Derecho',
                'verbose_name_plural': 'Derechos',
            },
        ),
    ]
