# Generated by Django 5.1.1 on 2024-09-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuil', models.IntegerField(unique=True)),
                ('apellido', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('direccion', models.TextField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=30)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('estado_consulta', models.CharField(choices=[('SOLTERO', 'soltero'), ('CASADO', 'casado'), ('DIVORCIADO', 'divorciado'), ('SEPARADO', 'separado'), ('VIUDO', 'viudo'), ('CONCUBINO', 'concubino')], max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
