# Generated by Django 5.1.1 on 2024-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_estado_consulta_cliente_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
