# Generated by Django 5.1.1 on 2024-09-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='contraseña1',
            field=models.TextField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contraseña2',
            field=models.TextField(max_length=12, null=True),
        ),
    ]
