# Generated by Django 5.1.1 on 2024-09-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_contraseña1_cliente_contraseña2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contraseña1',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contraseña2',
            field=models.CharField(max_length=12),
        ),
    ]
