# Generated by Django 5.1.1 on 2024-09-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_contraseña1_alter_cliente_contraseña2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contraseña1',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='contraseña2',
        ),
    ]
