# Generated by Django 5.1.1 on 2024-09-21 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0006_alter_cliente_contraseña1_alter_cliente_contraseña2'),
        ('derechos', '0001_initial'),
        ('nosotros', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.TextField(max_length=200)),
                ('fecha_consulta', models.DateTimeField(auto_now=True)),
                ('estado_consulta', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RESPONDIDA', 'Respondida')], default='PENDIENTE', max_length=10)),
                ('fecha_respuesta', models.DateTimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nosotros.nosotros')),
                ('cuil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clientes.cliente')),
                ('derecho', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='derechos.derecho')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
