# Generated by Django 5.1.1 on 2024-09-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0003_alter_consulta_fecha_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='fecha_respuesta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
