# Generated by Django 5.1.1 on 2024-09-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_avatar_userprofile_aimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='aimage',
            new_name='image',
        ),
    ]
