# Generated by Django 5.1.1 on 2024-09-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nosotros',
            name='matricula',
            field=models.TextField(max_length=30),
        ),
    ]
